version: '3.3'

services:
  rclone-vfs:
    image: rclone/rclone:latest
    container_name: rclone-vfs
    restart: unless-stopped
    privileged: true
    command: mount Papini:/movies /movies --dir-perms 755 --file-perms 755  --gid ${PGID} --uid ${PUID} --allow-other --buffer-size 32M --poll-interval 1m --log-file=/config/rclone/rclone.log --log-level=DEBUG
    volumes:
      - "${STORAGE_LOCATION}/radarr/movies/remote:/movies:shared"
      - "${STORAGE_LOCATION}/rclone-vfs:/config/rclone"
    environment:
      PHP_TZ: America/Argentina/Buenos_Aires
      PUID: 1000
      PGID: 1000
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN